name: Deploy Environments

on:
  push:
    branches:
      - main
      - production
      - development
      - testing

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: ./front-end
        run: npm install

      - name: Build React App
        working-directory: ./front-end
        run: npm run build

      - name: Deploy Production
        if: github.ref == 'refs/heads/production' || github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./front-end/dist
          keep_files: true
          cname: prod.luvetha.xyz

      - name: Deploy Development
        if: github.ref == 'refs/heads/development' || github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./front-end/dist
          destination_dir: development
          keep_files: true

      - name: Deploy Testing
        if: github.ref == 'refs/heads/testing' || github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./front-end/dist
          destination_dir: testing
          keep_files: true
